### ISSUE TITLE
'fewer data points than expected'

### ISSUE THREAD

**Issue by esthersmits** [R-Broadley/activpal_utils-matlab#2]
Hi,

I am using the load datx code and it has been working most of the time. I was just using it gave me the following error for the first time and it states 'please report this to the developers': 

Error using activpal_utils.load_datx>correct_length (line 287)
There are fewer data points than expected in file:
S:\SHRS-Research\Human Neuroscience Unit\Esther\EstherSmits_Backup\28day LBP - ActivPal Study\Participants\Data\ActivPAL\KH\KHtrunk-AP474936 22Feb17 12-00pm for 14d
19h 34m.datx
Please report this to the developers at:
https://github.com/R-Broadley/activpal_utils-matlab/issues

Error in activpal_utils.load_datx (line 109)
    [signals, Data.meta] = correct_length(signals, Data.meta, filePath);

Could you please help me with this issue? Also let me know if you need more information or the datafile that causes this issue.

Thank you!

Cheers,
Esther Smits

**Comment by R-Broadley** [comment]
Hi Esther

Thank you for reporting the issue.
This looks like one of the edge cases which I had never seen but checked for anyway.

Please could send me a private email me with one of the problem files I'll take a look and implement a solution.
